#! /bin/sh
# Script for running ott in instant client.
# Before running this script:
#   set jdk1.5/bin in your PATH
#   set LD_LIBRARY_PATH to include the directory containing the instant client 
#       libraries
#   set ottclasses.zip, ojdbc5.jar, orai18n.jar as part of your CLASSPATH

while [ $# -gt 0 ]
do
      case $1 in
      user*)
              OTTUSER="$OTTUSER $1"
              export OTTUSER ;;
      *)
              args="$args $1";;
      esac
shift
done

exec java oracle.ott.c.CMain nlslang=${NLS_LANG} $args
