#ifndef EXTCONF_H
#define EXTCONF_H
#define HAVE_OCIINITIALIZE 1
#define HAVE_TYPE_ORATEXT 1
#define HAVE_OCIENVCREATE 1
#define HAVE_OCITERMINATE 1
#define HAVE_OCILOBOPEN 1
#define HAVE_OCILOBCLOSE 1
#define HAVE_OCILOBCREATETEMPORARY 1
#define HAVE_OCILOBGETCHUNKSIZE 1
#define HAVE_OCILOBLOCATORASSIGN 1
#define HAVE_OCIROWIDTOCHAR 1
#define HAVE_OCIRESET 1
#endif
#define OCI8_MODULE_VERSION "1.0.6"
#define OCI8_CLIENT_VERSION "1020"
