desc "Install all third party linux_x64 libraries"
  task :default => ['linux_x86_32:oci8']

namespace :linux_x86_32 do 

  desc "Install linux_x86_32 ruby-oci8"
  task :oci8 => [:oracle_libs] do 
    puts "Installing ruby-oci8-1.0.6"
    cmd = "
         if [ -e $HOME/.rvm/bin/rvmsudo ]; then
           SUDO=$HOME/.rvm/bin/rvmsudo
         else
           SUDO=sudo
         fi 
         export ORACLE_HOME=/opt/oracle/instantclient_11_1;
         export PATH=$ORACLE_HOME:$PATH;
         cp -r ruby-oci8-1.0.6 /tmp/;
         cd /tmp/ruby-oci8-1.0.6;
         make; 
         $SUDO make install;
       "
    system(cmd) 
  end

  desc "Install Oracle Libraries"
  task :oracle_libs do
    puts "Installing Oracle libs"
    cmd = "
        if [ -e $HOME/.rvm/bin/rvmsudo ]; then
          SUDO=$HOME/.rvm/bin/rvmsudo
        else
          SUDO=sudo
        fi 
        $SUDO mkdir -p /opt/oracle ;
        $SUDO cp -r instantclient_11_1 /opt/oracle/;
        cd /opt/oracle/instantclient_11_1;
        $SUDO ln -s libclntsh.so.11.1 libclntsh.so
        $SUDO sh -c \"echo /opt/oracle/instantclient_11_1 > /etc/ld.so.conf.d/oracle.conf\"
        $SUDO ldconfig
      "
    system(cmd) 

  end

end
