namespace :ruby_oracle_libs do

  desc "Install all third party linux_x64 libraries"
  task :install => ['linux_x86_64:oci8']

  namespace :linux_x86_64 do 

    desc "Install linux_x86_64 ruby-oci8"
    task :oci8 => [:oracle_libs] do 
      puts "Installing ruby-oci8-1.0.6"
      cmd = "
         export ORACLE_HOME=/opt/oracle/instantclient_11_1;
         export PATH=$ORACLE_HOME:$PATH;
         cp -r ruby-oci8-1.0.6 /tmp/;
         cd /tmp/ruby-oci8-1.0.6;
         make; 
         sudo make install;
       "
       system(cmd) 
    end

    desc "Install Oracle Libraries"
    task :oracle_libs do
      puts "Installing Oracle libs"
      cmd = "
        sudo mkdir -p /opt/oracle ;
        sudo cp -r instantclient_11_1 /opt/oracle/;
        cd /opt/oracle/instantclient_11_1;
        sudo ln -s libclntsh.so.11.1 libclntsh.so
        sudo sh -c \"echo /opt/oracle/instantclient_11_1 > /etc/ld.so.conf.d/oracle.conf\"
        sudo ldconfig
      "
      system(cmd) 

    end

  end

end
